version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:dubnium

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths: .

  typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run type checker
          command: npm run typecheck

  prettier:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run prettier
          command: npm run prettier -- --list-different

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: npm run test -- --ci --coverage --runInBand
      - store_artifacts:
          path: coverage

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/project/.npmrc
      - run:
          name: Publish package
          command: npm publish --dry-run

workflows:
  version: 2
  test-deploy:
    jobs:
      - install
      - typecheck:
          requires:
            - install
      - prettier:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - typecheck
            - prettier
            - test
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
